### PR TITLE
Add support for with-credentials attribute

### PR DESCRIPTION
**Pull request by gustafnk**
TODO:

- verify
- (DONE) document in README.md

### CODE REVIEW

**Comment by dwestheide** [comment]
The change looks good to me. As promised, I can take care of testing this. However, I will need some time to set this up properly, which will likely take a lot longer than the implementation of this feature. I hope that's okay for you. :)

**Comment by gustafnk** [comment]
No worries :) My own idea is to use the test server (see package.json) and alternate between localhost and 127.0.0.1 to represent a failing request and then see if the attribute makes the request succeed.

**Comment by gustafnk** [comment]
Ugh, testing this was harder than I thought. I just did a visual test with `console.log` and the different cases seem to kick in as I expected.

**Comment by dwestheide** [comment]
Didn't know about the test server, so I wrote up my own two little servers, using the same approach. It works fine in Chrome and Safari, but it seems that Firefox is not sending the cookie. :( I haven't had time to debug this yet. If you have time, maybe you can try this with the test server as well.

**Comment by gustafnk** [comment]
I guess that it's the same [testing?] problems in @mnot's `hinclude` as well then...

**Comment by gustafnk** [comment]
@dwestheide Can you verify that `hinclude` has the same problem in FF?

**Comment by dwestheide** [comment]
@gustafnk Yes, I can give it a try with `hinclude` as well. However, I will have to postpone that to another day. Hopefully tomorrow.

**Comment by dwestheide** [comment]
BTW, I did some debugging and found that the `withCredentials` attribute on the request is set correctly in FF. It just seems to be ignored.

Tomorrow, I will try to see if the behaviour is the same in FF for `hinclude`.

**Comment by gustafnk** [comment]
Cool 👍

**Comment by dwestheide** [comment]
@gustafnk Okay, the FF problem was my own fault, because I had disabled third-party cookies completely. Setting it to accept third-party cookies from sites already visited did the trick.

**Comment by gustafnk** [comment]
Allright, great. I'll merge then.

**Pull request merged**
